apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: '4.0.1'
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: default
      interval: 1m
  values:
    replicaCount: 1
    
  # Enable Drift Detection
  driftDetection:
    mode: enabled
    # ignore:
    #  - paths: ["/spec/replicas"]
