apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-only-rolebinding
  namespace: flux-system
subjects:
- kind: ServiceAccount
  name: alice
  namespace: flux-system
roleRef:
  kind: Role
  name: read-only-role
  apiGroup: rbac.authorization.k8s.io
