apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml

# permissions
- accounts/alice-service-acc.yaml
- accounts/init-password.yaml
- RBAC/rbac_read-only-role.yaml
- RBAC/read-only-rolebinding.yaml
